<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="FluentResults" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../SharedKernel/ModulithTemplate.SharedKernel.Web/ModulithTemplate.SharedKernel.Web.csproj" />
    <ProjectReference Include="../ModulithTemplate.Features.Orders.Application/ModulithTemplate.Features.Orders.Application.csproj" />
    <ProjectReference Include="../ModulithTemplate.Features.Orders.Infrastructure/ModulithTemplate.Features.Orders.Infrastructure.csproj" />
  </ItemGroup>

</Project>
