<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <PackageReference Include="bunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../src/Features/Orders/ModulithTemplate.Features.Orders.Web/ModulithTemplate.Features.Orders.Web.csproj" />
  </ItemGroup>

</Project>
