<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <PackageReference Include="bunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../src/Features/FeatureName/ModulithApp.Features.FeatureName.Web/ModulithApp.Features.FeatureName.Web.csproj" />
  </ItemGroup>

</Project>
