<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="EntityFrameworkCore.Exceptions.PostgreSQL" />
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Underground.Outbox" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ModulithTemplate.SharedKernel.Domain/ModulithTemplate.SharedKernel.Domain.csproj" />
    <ProjectReference Include="../ModulithTemplate.SharedKernel.Outbox/ModulithTemplate.SharedKernel.Outbox.csproj" />
  </ItemGroup>

</Project>
