<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="FluentResults" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ModulithTemplate.Features.Orders.Domain/ModulithTemplate.Features.Orders.Domain.csproj" />
  </ItemGroup>

</Project>
