<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ModulithApp.Features.FeatureName.Domain/ModulithApp.Features.FeatureName.Domain.csproj" />
    <ProjectReference Include="../../../SharedKernel/ModulithApp.SharedKernel.Domain/ModulithApp.SharedKernel.Domain.csproj" />
    <ProjectReference Include="../../../SharedKernel/ModulithApp.SharedKernel.Infrastructure/ModulithApp.SharedKernel.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data/Migrations/" />
  </ItemGroup>

</Project>
