<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ModulithApp.Features.FeatureName.Domain/ModulithApp.Features.FeatureName.Domain.csproj" />
    <ProjectReference Include="../../../ModulithApp.Domain.Common/ModulithApp.Domain.Common.csproj" />
    <ProjectReference Include="../../../ModulithApp.Infrastructure.Common/ModulithApp.Infrastructure.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data/Migrations/" />
  </ItemGroup>

</Project>
